2024-12-08 21:30:51,404 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\Users\Vladimir\PycharmProjects\Urban_HW\module 12\12_4\tests_12_4.py", line 28, in test_run
    run = Runner(123)
          ^^^^^^^^^^^
  File "C:\Users\Vladimir\PycharmProjects\Urban_HW\module 12\12_4\rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-12-08 21:30:51,405 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\Users\Vladimir\PycharmProjects\Urban_HW\module 12\12_4\tests_12_4.py", line 16, in test_walk
    run = Runner('Vova', -2)
          ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vladimir\PycharmProjects\Urban_HW\module 12\12_4\rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -2
